#!/usr/bin/env node
/**
 * seed-games.js
 *
 * Reads data/games-batch-1.json and prints SQL INSERT statements to stdout.
 * Paste the output into the Supabase SQL editor.
 *
 * Usage:
 *   node scripts/seed-games.js
 *   node scripts/seed-games.js > insert-games.sql   # save to file
 */

const fs   = require('fs');
const path = require('path');

const dataFile = path.resolve(__dirname, '../data/games-batch-1.json');

let games;
try {
  games = JSON.parse(fs.readFileSync(dataFile, 'utf8'));
} catch (err) {
  console.error('Failed to read data file:', err.message);
  process.exit(1);
}

// Escape single quotes for SQL string literals
function esc(str) {
  return String(str).replace(/'/g, "''");
}

const lines = games.map((g) =>
  `INSERT INTO games (game_number, date, answer_player, clue_1, clue_2, clue_3, clue_4, clue_5, clue_6)\n` +
  `VALUES (\n` +
  `  ${g.game_number},\n` +
  `  '${g.date}',\n` +
  `  '${esc(g.answer_player)}',\n` +
  `  '${esc(g.clue_1)}',\n` +
  `  '${esc(g.clue_2)}',\n` +
  `  '${esc(g.clue_3)}',\n` +
  `  '${esc(g.clue_4)}',\n` +
  `  '${esc(g.clue_5)}',\n` +
  `  '${esc(g.clue_6)}'\n` +
  `);`
);

console.log('-- FootyIQ games batch 1 (games 2–31, 2026-04-16 to 2026-05-15)');
console.log('-- Generated by scripts/seed-games.js');
console.log('');
console.log(lines.join('\n\n'));
console.log('');
console.log(`-- ${games.length} games inserted.`);
